apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: {{ .Values.ingress.host}}
   http:
     paths:
     - path: /
       backend:
         serviceName: {{ include "kbs-front.fullname" . }}
         servicePort: 80