x-db-access:
  username: &dbUsername skgijpsbxmxmkruipzfm      
  password: &dbPassword tqklal9i71uy6shxhi0w      


kbs-front:
  image:
    repository: kbs-front
    tag: "753fe2f"
  ingress:
    host: 'kbs-front.io'

kbs-api:
  replicaCount: 2
  image:
    repository: kbs-api
    tag: "a2c8ee7"
  config:
    jwtSecret: "vGYO6cAYut9jyV9u77j"
    dbConn: "Host=state-kbs-db;Database=kbs;Username=skgijpsbxmxmkruipzfm;Password=tqklal9i71uy6shxhi0w"
    cors: "http://kbs-front.io"

kbs-schema:  
  image:
    repository: kbs-schema
    tag: "a2c8ee7"
  config:    
    dbConn: "Host=state-kbs-db;Database=kbs;Username=skgijpsbxmxmkruipzfm;Password=tqklal9i71uy6shxhi0w"    
