apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kbs-api.fullname" . }}
  labels:
{{ include "kbs-api.labels" . | indent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kbs-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kbs-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          - name: "jwtConfig__secret"
            value: {{ .Values.config.jwtSecret | quote }}
          - name: "CorsConfig__Allowed"
            value: {{ .Values.config.cors | quote }}
          - name: "ConnectionStrings__Main"
            value: {{ .Values.config.dbConn | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP          
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
