apiVersion: v1
kind: Service
metadata:
  name: {{ include "kbs-api.fullname" . }}
  labels:
{{ include "kbs-api.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kbs-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
